[package]
name = "defining_and_instantiating_structs"
version = "0.1.0"
authors = ["kecci <kecci@machtwatch.co.id>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
